class var:
    rodape ="""
            <div>
            <p style="color:#222222;font-size:small;font-family:Arial,Helvetica,sans-serif;background-color:white;margin:0;"><i><span style="color:#3399FF;font-family:Arial Narrow,sans-serif;">Atenciosamente,<u></u><u></u></span></i></p>
            <p style="background-color:white;margin:0;"><font color="#3399FF" face="Arial Narrow,sans-serif"><span style="font-size:18.67px;"><b>Hector Pérez</b></span></font></p>
            <p style="color:#222222;font-size:small;font-family:Arial,Helvetica,sans-serif;background-color:white;margin:0;"><span lang="en-US" style="color:#3399FF;font-size:13pt;font-family:Arial Narrow,sans-serif;">Consultor / Infraestrutura de TI</span></p>
            <p style="color:#222222;font-size:small;font-family:Arial,Helvetica,sans-serif;background-color:white;margin:0;"><span lang="en-US" style="color:#3399FF;font-size:13pt;font-family:Arial Narrow,sans-serif;"><img data-imagetype="AttachmentByCid" originalsrc="cid:2bba49a3-b9e7-44fd-aaf3-825050d383d2" data-custom="AAMkAGRlZjMyNzIxLThhODMtNGQzMC1hZThhLTlmN2MzMjY5OTFkMQBGAAAAAADWNrYdP4dbQYEJ%2FD7kHszyBwDfr9Uv5FLJS5%2BAAwWCavC0AAAAAAEJAADfr9Uv5FLJS5%2BAAwWCavC0AAAxadzLAAABEgAQAFDXesw0%2BPVMhQS%2FtP2lxBg%3D" naturalheight="0" naturalwidth="0" src="https://attachments.office.net/owa/hector.perez%40oraex.com/service.svc/s/GetAttachmentThumbnail?id=AAMkAGRlZjMyNzIxLThhODMtNGQzMC1hZThhLTlmN2MzMjY5OTFkMQBGAAAAAADWNrYdP4dbQYEJ%2FD7kHszyBwDfr9Uv5FLJS5%2BAAwWCavC0AAAAAAEJAADfr9Uv5FLJS5%2BAAwWCavC0AAAxadzLAAABEgAQAFDXesw0%2BPVMhQS%2FtP2lxBg%3D&amp;thumbnailType=2&amp;token=eyJhbGciOiJSUzI1NiIsImtpZCI6IkQ4OThGN0RDMjk2ODQ1MDk1RUUwREZGQ0MzODBBOTM5NjUwNDNFNjQiLCJ0eXAiOiJKV1QiLCJ4NXQiOiIySmozM0Nsb1JRbGU0Tl84dzRDcE9XVUVQbVEifQ.eyJvcmlnaW4iOiJodHRwczovL291dGxvb2sub2ZmaWNlLmNvbSIsInVjIjoiMDJmZjhhZmNhMGQ0NDM2Njg3MGZlMzg4NDI1MzYwMzUiLCJzaWduaW5fc3RhdGUiOiJbXCJrbXNpXCJdIiwidmVyIjoiRXhjaGFuZ2UuQ2FsbGJhY2suVjEiLCJhcHBjdHhzZW5kZXIiOiJPd2FEb3dubG9hZEAwYTE3NWVlYS0wMDRhLTQ2NWItOGQxYi04NDc2MjVjMTFmZmEiLCJpc3NyaW5nIjoiV1ciLCJhcHBjdHgiOiJ7XCJtc2V4Y2hwcm90XCI6XCJvd2FcIixcInB1aWRcIjpcIjExNTM4MDExMjI3NzkzOTM3MjRcIixcInNjb3BlXCI6XCJPd2FEb3dubG9hZFwiLFwib2lkXCI6XCJkNTJmYWY5Yy02NTdkLTQwZGItYmQzNC1kNGU0OGVhZDc4MzVcIixcInByaW1hcnlzaWRcIjpcIlMtMS01LTIxLTIxNTQ1MDg1OTAtMzcyNTkyMzE1NC0yMzc5NzMwMTE3LTM0MjgwNzE3XCJ9IiwibmJmIjoxNjY0MzE5OTcxLCJleHAiOjE2NjQzMjA1NzEsImlzcyI6IjAwMDAwMDAyLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMEAwYTE3NWVlYS0wMDRhLTQ2NWItOGQxYi04NDc2MjVjMTFmZmEiLCJhdWQiOiIwMDAwMDAwMi0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvYXR0YWNobWVudHMub2ZmaWNlLm5ldEAwYTE3NWVlYS0wMDRhLTQ2NWItOGQxYi04NDc2MjVjMTFmZmEiLCJoYXBwIjoib3dhIn0.Xo30WyRMfKL5cDpHg1ybNt5H5nC_WNCDhzClwbGyVv_2EqfCGwmwKOMlzskscHUkoeNva4QrPGcEyGhZQzUdDZ1dBfAgzZCVmUYKC-gwsPdQmroMKsv4XN_AUJ4gjVYECLu5621hy3p4l_d7aW-yPWv-bx53wVCgrJ97D2G8Q9F5FG168Szivmb-I-pD-59ruV4xtXfR3SJg306loITVjCxN-YIIwH_DvtcJCCtLTATDUnquWG13tuRxuT7MyTxV1MtBNagoExQlgAhfoLfUH9_BgULoxjmqfvHz7TvQfhLGk5GlCKDWHMuGsv_ext9pUHQIi2n9_FNRtW-CADZ1Pg&amp;X-OWA-CANARY=4Ix3eontNUu9bFYbt3Q_5lBRIArdoNoYV2tOYqftPP7t5Oyqv1aCu6YUcrJLVZ5q7oRbLwjzSP0.&amp;owa=outlook.office.com&amp;scriptVer=20220916007.07&amp;animation=true" data-outlook-trace="F:1|T:1" style="max-width: 100%; cursor: pointer; min-width: auto; min-height: auto; height: auto;" crossorigin="use-credentials" class="ADIae">&nbsp;+55 61 9 9155-7667<br aria-hidden="true">
            </span></p>
            <p style="color:#222222;font-size:small;font-family:Arial,Helvetica,sans-serif;background-color:white;margin:0;"><span lang="en-US" style="color:#3399FF;font-size:13pt;font-family:Arial Narrow,sans-serif;"><img data-imagetype="AttachmentByCid" originalsrc="cid:db192afe-9b03-4b3d-b239-9743808d6995" data-custom="AAMkAGRlZjMyNzIxLThhODMtNGQzMC1hZThhLTlmN2MzMjY5OTFkMQBGAAAAAADWNrYdP4dbQYEJ%2FD7kHszyBwDfr9Uv5FLJS5%2BAAwWCavC0AAAAAAEJAADfr9Uv5FLJS5%2BAAwWCavC0AAAxadzLAAABEgAQANwHIK6lXfZPsYmgFiyOdvg%3D" naturalheight="0" naturalwidth="0" src="https://attachments.office.net/owa/hector.perez%40oraex.com/service.svc/s/GetAttachmentThumbnail?id=AAMkAGRlZjMyNzIxLThhODMtNGQzMC1hZThhLTlmN2MzMjY5OTFkMQBGAAAAAADWNrYdP4dbQYEJ%2FD7kHszyBwDfr9Uv5FLJS5%2BAAwWCavC0AAAAAAEJAADfr9Uv5FLJS5%2BAAwWCavC0AAAxadzLAAABEgAQANwHIK6lXfZPsYmgFiyOdvg%3D&amp;thumbnailType=2&amp;token=eyJhbGciOiJSUzI1NiIsImtpZCI6IkQ4OThGN0RDMjk2ODQ1MDk1RUUwREZGQ0MzODBBOTM5NjUwNDNFNjQiLCJ0eXAiOiJKV1QiLCJ4NXQiOiIySmozM0Nsb1JRbGU0Tl84dzRDcE9XVUVQbVEifQ.eyJvcmlnaW4iOiJodHRwczovL291dGxvb2sub2ZmaWNlLmNvbSIsInVjIjoiMDJmZjhhZmNhMGQ0NDM2Njg3MGZlMzg4NDI1MzYwMzUiLCJzaWduaW5fc3RhdGUiOiJbXCJrbXNpXCJdIiwidmVyIjoiRXhjaGFuZ2UuQ2FsbGJhY2suVjEiLCJhcHBjdHhzZW5kZXIiOiJPd2FEb3dubG9hZEAwYTE3NWVlYS0wMDRhLTQ2NWItOGQxYi04NDc2MjVjMTFmZmEiLCJpc3NyaW5nIjoiV1ciLCJhcHBjdHgiOiJ7XCJtc2V4Y2hwcm90XCI6XCJvd2FcIixcInB1aWRcIjpcIjExNTM4MDExMjI3NzkzOTM3MjRcIixcInNjb3BlXCI6XCJPd2FEb3dubG9hZFwiLFwib2lkXCI6XCJkNTJmYWY5Yy02NTdkLTQwZGItYmQzNC1kNGU0OGVhZDc4MzVcIixcInByaW1hcnlzaWRcIjpcIlMtMS01LTIxLTIxNTQ1MDg1OTAtMzcyNTkyMzE1NC0yMzc5NzMwMTE3LTM0MjgwNzE3XCJ9IiwibmJmIjoxNjY0MzE5OTcxLCJleHAiOjE2NjQzMjA1NzEsImlzcyI6IjAwMDAwMDAyLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMEAwYTE3NWVlYS0wMDRhLTQ2NWItOGQxYi04NDc2MjVjMTFmZmEiLCJhdWQiOiIwMDAwMDAwMi0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvYXR0YWNobWVudHMub2ZmaWNlLm5ldEAwYTE3NWVlYS0wMDRhLTQ2NWItOGQxYi04NDc2MjVjMTFmZmEiLCJoYXBwIjoib3dhIn0.Xo30WyRMfKL5cDpHg1ybNt5H5nC_WNCDhzClwbGyVv_2EqfCGwmwKOMlzskscHUkoeNva4QrPGcEyGhZQzUdDZ1dBfAgzZCVmUYKC-gwsPdQmroMKsv4XN_AUJ4gjVYECLu5621hy3p4l_d7aW-yPWv-bx53wVCgrJ97D2G8Q9F5FG168Szivmb-I-pD-59ruV4xtXfR3SJg306loITVjCxN-YIIwH_DvtcJCCtLTATDUnquWG13tuRxuT7MyTxV1MtBNagoExQlgAhfoLfUH9_BgULoxjmqfvHz7TvQfhLGk5GlCKDWHMuGsv_ext9pUHQIi2n9_FNRtW-CADZ1Pg&amp;X-OWA-CANARY=4Ix3eontNUu9bFYbt3Q_5lBRIArdoNoYV2tOYqftPP7t5Oyqv1aCu6YUcrJLVZ5q7oRbLwjzSP0.&amp;owa=outlook.office.com&amp;scriptVer=20220916007.07&amp;animation=true" data-outlook-trace="F:1|T:1" style="max-width: 100%; cursor: pointer; min-width: auto; min-height: auto; height: auto;" crossorigin="use-credentials" class="ADIae">&nbsp;<a href="mailto:hector.perez@oraex.com" target="_blank" rel="noopener noreferrer" data-auth="NotApplicable" title="hector.perez@oraex.com" data-safelink="true" data-linkindex="0">hector.perez@oraex.com</a><br aria-hidden="true">
            <img data-imagetype="AttachmentByCid" originalsrc="cid:13d8d6a5-cdca-466c-b85e-7a64463bb1f0" data-custom="AAMkAGRlZjMyNzIxLThhODMtNGQzMC1hZThhLTlmN2MzMjY5OTFkMQBGAAAAAADWNrYdP4dbQYEJ%2FD7kHszyBwDfr9Uv5FLJS5%2BAAwWCavC0AAAAAAEJAADfr9Uv5FLJS5%2BAAwWCavC0AAAxadzLAAABEgAQAF88%2BGTAKWJEgU3H0qeC0WQ%3D" naturalheight="0" naturalwidth="0" src="https://attachments.office.net/owa/hector.perez%40oraex.com/service.svc/s/GetAttachmentThumbnail?id=AAMkAGRlZjMyNzIxLThhODMtNGQzMC1hZThhLTlmN2MzMjY5OTFkMQBGAAAAAADWNrYdP4dbQYEJ%2FD7kHszyBwDfr9Uv5FLJS5%2BAAwWCavC0AAAAAAEJAADfr9Uv5FLJS5%2BAAwWCavC0AAAxadzLAAABEgAQAF88%2BGTAKWJEgU3H0qeC0WQ%3D&amp;thumbnailType=2&amp;token=eyJhbGciOiJSUzI1NiIsImtpZCI6IkQ4OThGN0RDMjk2ODQ1MDk1RUUwREZGQ0MzODBBOTM5NjUwNDNFNjQiLCJ0eXAiOiJKV1QiLCJ4NXQiOiIySmozM0Nsb1JRbGU0Tl84dzRDcE9XVUVQbVEifQ.eyJvcmlnaW4iOiJodHRwczovL291dGxvb2sub2ZmaWNlLmNvbSIsInVjIjoiMDJmZjhhZmNhMGQ0NDM2Njg3MGZlMzg4NDI1MzYwMzUiLCJzaWduaW5fc3RhdGUiOiJbXCJrbXNpXCJdIiwidmVyIjoiRXhjaGFuZ2UuQ2FsbGJhY2suVjEiLCJhcHBjdHhzZW5kZXIiOiJPd2FEb3dubG9hZEAwYTE3NWVlYS0wMDRhLTQ2NWItOGQxYi04NDc2MjVjMTFmZmEiLCJpc3NyaW5nIjoiV1ciLCJhcHBjdHgiOiJ7XCJtc2V4Y2hwcm90XCI6XCJvd2FcIixcInB1aWRcIjpcIjExNTM4MDExMjI3NzkzOTM3MjRcIixcInNjb3BlXCI6XCJPd2FEb3dubG9hZFwiLFwib2lkXCI6XCJkNTJmYWY5Yy02NTdkLTQwZGItYmQzNC1kNGU0OGVhZDc4MzVcIixcInByaW1hcnlzaWRcIjpcIlMtMS01LTIxLTIxNTQ1MDg1OTAtMzcyNTkyMzE1NC0yMzc5NzMwMTE3LTM0MjgwNzE3XCJ9IiwibmJmIjoxNjY0MzE5OTcxLCJleHAiOjE2NjQzMjA1NzEsImlzcyI6IjAwMDAwMDAyLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMEAwYTE3NWVlYS0wMDRhLTQ2NWItOGQxYi04NDc2MjVjMTFmZmEiLCJhdWQiOiIwMDAwMDAwMi0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvYXR0YWNobWVudHMub2ZmaWNlLm5ldEAwYTE3NWVlYS0wMDRhLTQ2NWItOGQxYi04NDc2MjVjMTFmZmEiLCJoYXBwIjoib3dhIn0.Xo30WyRMfKL5cDpHg1ybNt5H5nC_WNCDhzClwbGyVv_2EqfCGwmwKOMlzskscHUkoeNva4QrPGcEyGhZQzUdDZ1dBfAgzZCVmUYKC-gwsPdQmroMKsv4XN_AUJ4gjVYECLu5621hy3p4l_d7aW-yPWv-bx53wVCgrJ97D2G8Q9F5FG168Szivmb-I-pD-59ruV4xtXfR3SJg306loITVjCxN-YIIwH_DvtcJCCtLTATDUnquWG13tuRxuT7MyTxV1MtBNagoExQlgAhfoLfUH9_BgULoxjmqfvHz7TvQfhLGk5GlCKDWHMuGsv_ext9pUHQIi2n9_FNRtW-CADZ1Pg&amp;X-OWA-CANARY=4Ix3eontNUu9bFYbt3Q_5lBRIArdoNoYV2tOYqftPP7t5Oyqv1aCu6YUcrJLVZ5q7oRbLwjzSP0.&amp;owa=outlook.office.com&amp;scriptVer=20220916007.07&amp;animation=true" data-outlook-trace="F:1|T:1" style="max-width: 100%; cursor: pointer; min-width: auto; min-height: auto; height: auto;" crossorigin="use-credentials" class="ADIae"><br aria-hidden="true">
            </span></p></div>
            """
    cc_enc_valid = " execucaodemudancas@getnet.com.br; planejamentodemudancas@getnet.com.br; gestao_mudanca@getnet.com.br; suporte@oraex.com; infra_requisicoes_incidentes@getnet.com.br;"
    cc_cancel_ins = "governanca_ti@getnet.com.br; execucaodemudancas@getnet.com.br; planejamentodemudancas@getnet.com.br; soc@getnet.com.br; gestao_mudanca@getnet.com.br; infra_requisicoes_incidentes@getnet.com.br; integracao_demandas@getnet.com.br; suporte@oraex.com"
    cc_teste = "hectordavidrezende@gmail.com; hectordavidrezende@outlook.com.br"
    lista_teste = ['validacao' ,'hectordavidrezende@gmail.com', 'CHGTANANAN', 'GNCANNL5605 - linux/database', ' A aplicação de patches de S.O. foi realizada com sucesso. Reboot realizado com sucesso e nenhum patch pendente.']





