config:
  email_signature:
    name: '.'
    job: '.'
    phone_number: '.'
    email: '.'


  paths:
    path_to_prints: ''
    path_to_excel: ''


  excel_columns_config:
    emailTo: ''
    closure: ''
    gmud: ''
    adequacy: ''
    host: ''
    primaryContactEmail: ''
    description: ''
    preCheck: ''
    afterCheck: ''


  email_configure:
    success_copy: ''
    canceled_insuccesss_copy: ''